### PR TITLE
Display stars in issue

### LINKED ISSUE #25: Display/filter project by stars or forks
Looking for a meaningful project to contribute to, it would be useful to know the impact of the listed repositories. If you approve this enhancement I can do it next week. If not someone else can take it

### LINKED ISSUE #26: Navigation button heights are too long
**Current Behavior:**
The navigation buttons are clickable below the displayed button.
image

**Desired Behavior:**
Reduce the height of the button to match the displayed button.

If this is a valid issue, can I please work on it? Thank you.

### PR DESCRIPTION
**Pull request by devjuliet**
Description: Displays stars in issue below the name of the repository

- [x] Called StargazerCount in the repository in Github GraphQL API
- [x] Added file svg of star to display in UI
- [x] Created method to return stars of specific repository
- [x] Displays the number of stars in UI

Closes #25

### CODE REVIEW

**Comment by darensin01** [comment]
Hi, thanks for your PR! Could you make the following changes:

1. This is a little misleading, but the changes in the Go file should be in main-to-file.go instead (see .github/workflows, where the Go file is executed several times a day)
2. Would be great if you could also push an updated version of the data (backend/data.json), so that when this PR is merged, the JS file will not run into errors (e.g. can't read the stars property in the JSON file)

**Comment by devjuliet** [comment]
Great! Working on it! 😄

**Comment by darensin01** [comment]
Can you also push a copy of data.json?

**Comment by devjuliet** [comment]
Yes! I'm working with some of my local environment 😄

**Comment by darensin01** [comment]
thanks! :)

**Pull request merged**
